# Define 'Secret' to store db-credentials 
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials # Name of the 'Secret'
data:
  username: YWJoaQ==  # base64 encoded 'Secret' username
  password: YWJoaTE0Mw== # base64 encoded 'Secret' password
