
# Define 'Service' to expose backend application deployment
apiVersion: v1
kind: Service
metadata:
  name: bank-transaction
spec:
  selector:  # backend application pod lables should match these
    app: bank-transaction
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8094
    targetPort: 8094
  type: LoadBalancer   # use NodePort, if you are not running Kubernetes on cloud
---
# Configure 'Deployment' of backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transaction
  labels: 
    app: bank-transaction
    tier: backend
spec:
  replicas: 1    # Number of replicas of back-end application to be deployed
  selector:
    matchLabels: # backend application pod labels should match these
      app: bank-transaction
      tier: backend
  template:
    metadata:
      labels: # Must macth 'Service' and 'Deployment' labels
        app: bank-transaction
        tier: backend  
    spec:                 
      containers: 
      - name: bank-transaction
        image: gcr.io/nodal-wall-298014/bank-transaction:v3
        ports:
        - containerPort: 8094

